[package]
name = "vanaddy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-client = "1.8"
solana-sdk = "1.8"
rayon = "1.5"
csv = "1.1"
